version: "3"
services:
  server:
    build: ./
    environment:
      MARIADB_USERNAME: "root"
      MARIADB_PASSWORD: "pass"
      MARIADB_HOSTNAME: mysql
      MARIADB_PORT: "3306"
      MARIADB_DATABASE: "yuri_bot"
      FEED_URL: "http://yurinavi.com/feed"
      TRAQ_WEBHOOK_ID:
      TRAQ_WEBHOOK_SECRET:
      X_TRAQ_Channel_Id:
    links:
      - mysql
    ports:
      - "3002:3002"
    restart: always
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: "pass"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"