version: "3"
services:
  server:
    build: ./
    environment:
      MARIADB_USERNAME: "root"
      MARIADB_PASSWORD: "pass"
      MARIADB_HOSTNAME: mysql
      MARIADB_PORT: "3306"
      MARIADB_DATABASE: "yuri_bot"
    links:
      - mysql
    ports:
      - "3000:3000"
    restart: always
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: "pass"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    volumes:
      - ./mysql/data:/var/lib/mariadb
      - ./mysql/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"